// Generated by LiveScript 1.4.0
(function(){
  var mvc, routeRegex;
  mvc = require('../');
  mvc.route(null, null);
  routeRegex == null && (routeRegex = /.*controller(?=\.).*/i);
  console.warn(routeRegex.test("aa_controller.js"));
}).call(this);
