// Generated by LiveScript 1.2.0
(function(){
  var index, user;
  this.index = index = (function(){
    index.displayName = 'index';
    var prototype = index.prototype, constructor = index;
    index.get = function(req, res, next){
      return res.send('get home/index');
    };
    function index(){}
    return index;
  }());
  this.user = user = (function(){
    user.displayName = 'user';
    var prototype = user.prototype, constructor = user;
    user.get = function(req, res, next){
      return res.send('get home/user');
    };
    user.post = function(req, res, next){
      return res.send('post home/user');
    };
    function user(){}
    return user;
  }());
}).call(this);
