// Generated by LiveScript 1.4.0
(function(){
  var fs, path, _;
  fs = require('fs');
  path = require('path');
  _ = require('lodash');
  /**
  * @params: path     # path
  */
  module.exports = function(dir){
    var root, getConfigureFileSync, configures, results, i$, len$, item, configure;
    root = process.cwd();
    if (!dir) {
      dir = path.join(root, 'configure');
      console.warn("warn: please set dir or load default -> dir: " + dir);
    }
    getConfigureFileSync = function(dir){
      var files, configure_files, configures;
      files = fs.readdirSync(dir);
      configure_files = _.filter(files, function(item){
        return /.*(?=\.json)/i.test(item);
      });
      return configures = _.map(configure_files, function(item){
        return item;
      });
    };
    configures = getConfigureFileSync(dir);
    if (!configures) {
      throw new Error("can not read configure directory: " + dir);
    }
    results = {};
    for (i$ = 0, len$ = configures.length; i$ < len$; ++i$) {
      item = configures[i$];
      configure = require(path.join(dir, item));
      results[item.replace(/\..*/i, '') + ""] = configure;
    }
    return results;
  };
}).call(this);
