// Generated by LiveScript 1.2.0
/**
* @params: options {
*   routeDir         # route dir path
*   routeRegex       # route regex
*   controllerDir    # controller dir path
*   controllerRegex  # controller regex
* }
*/
(function(){
  module.exports = function(app, options){};
}).call(this);
