// Generated by LiveScript 1.4.0
(function(){
  var path;
  path = require('path');
  /**
  * @params: settings {
  *   routeDir                  # route dir path
  *   controllerDir             # controller dir path
  *   configureDir              # configure dir path
  * }
  */
  module.exports = {
    route: require('./route'),
    configure: require('./configure'),
    module: require('./module'),
    loadModule: require('./module/load'),
    routeModule: require('./module/route'),
    _modules: require('./module/_modules')
  };
}).call(this);
