// Generated by LiveScript 1.4.0
(function(){
  var path;
  path = require('path');
  /**
  * @params: settings {
  *   routeDir                  # route dir path
  *   controllerDir             # controller dir path
  *   configureDir              # configure dir path
  * }
  */
  module.exports = {
    route: require('./route'),
    module: require('./module'),
    configure: require('./configure')
  };
}).call(this);
