// Generated by LiveScript 1.2.0
(function(){
  var mvc, homeController, testController;
  mvc = require('../');
  homeController = require('./lib/controllers/home_controller');
  testController = require('./lib/controllers/test_controller');
  mvc.route(null, function(data){
    return console.log(data);
  });
}).call(this);
