// Generated by LiveScript 1.4.0
(function(){
  var path, _modules;
  path = require('path');
  _modules = require('./_modules');
  exports.route = function(next){
    var ms, i$, ref$, len$, module, j$, ref1$, len1$, m;
    ms = [];
    for (i$ = 0, len$ = (ref$ = _modules).length; i$ < len$; ++i$) {
      module = ref$[i$];
      for (j$ = 0, len1$ = (ref1$ = module._module).length; j$ < len1$; ++j$) {
        m = ref1$[j$];
        ms.push({
          path: path.join(module._root || '', m.path),
          method: m.method,
          action: m.action,
          before: module.before,
          after: module.after
        });
      }
    }
    return next(ms);
  };
}).call(this);
